---
# handlers file for ansible-prometheus-exporters

- name: restart consul
  command: docker restart consul172
  delegate_to: "{{ consul_host }}"
  run_once: true

- name: restart exporters
  systemd:
    service: "{{ item.name }}.service"
    daemon_reload: true
    enabled: true
    state: restarted
  with_items:
    - "{{ exporters }}"
